### ISSUE TITLE
http资源缓存策略

### ISSUE THREAD

**Issue by twinkle77** [twinkle77/Knowledge-sharing#10]
* 讲述Cache-Control与Last-Modified的区别?
* 有了Last-Modified,为什么还要Etag?
* 有了Etag,为什么还要Last-Modified?
* Etag是怎么生成的？
* Expires的缺点

**Comment by sinner77** [comment]
http://www.cnblogs.com/vajoy/p/5341664.html，只过了一遍，大概懂了，明天我做下笔记然后发上答案

**Comment by sinner77** [comment]
http://www.cnblogs.com/vajoy/p/5341664.html
只过了一遍，大概懂了，明天我做下笔记然后发上答案

**Comment by sinner77** [comment]
## http缓存策略
| http报文中与缓存相关的字段 | |
| :--- | :---: |
| **通用首部字段** | |
| Cache-Control | 控制缓存的行为 |
| Pragma | http1.0遗留下来的，值为"no-cache"时禁用缓存 |
| **请求首部字段** | |
| If-Match | 比较ETag是否一致 |
| If-None-Match | 比较ETag是否一致 |
| If-Modified-Since | 比较资源最后更新的时间是否一致 |
| If-Unmodified-Since | 比较资源最后更新的时间是否一致 |
| **响应首部字段** | |
| ETag | 资源的匹配信息 |
| **实体首部字段** | |
| Expires | http1.0遗留下来的，实体主体过期的时间 |
| Last-Modified | 资源最后一次修改的时间 |


### http1.0时代
1.Pragma 禁用缓存(通用)
客户端使用：需要在html插入meta元标签,但这种禁用缓存的形式用处很有限
```html
<meta http-equiv="Prama" content="no-cache">
```
> 1. 仅有IE才能识别这段meta标签含义，其它主流浏览器仅能识别“Cache-Control: no-store”的meta标签（见出处）。
2. 在IE中识别到该meta标签含义，并不一定会在请求字段加上Pragma，但的确会让当前页面每次都发新请求（仅限页面，页面上的资源则不受影响）。


服务器使用：即在响应报文加上Pragma:no-cache,浏览器在收到服务器的Pragma字段后会对资源进行标记，禁用其缓存行为，进而后续每次刷新页面均能重新发出请求而不走缓存。
2.Expires 启用缓存(非通用)
```
//对应一个GMT（格林尼治时间）,告诉浏览器资源的缓存过期时间，如果没有过该时间点则不发请求
Expires: Mon, 22 Jul 2002 11:12:01 GMT
```
客户端使用：需要在html插入meta元标签,只有IE能识别
```
<meta http-equiv="expires" content="mon, 18 apr 2016 14:30:00 GMT">
```
服务端使用：在响应报头返回Expires字段，则在任何浏览器中都能正确设置资源缓存的时间,需要注意的是，响应报头中Expires所定义的缓存时间是相对服务器上的时间而言的，如果客户端上的时间跟服务器上的时间不一致（特别是用户修改了自己电脑的系统时间），那缓存时间可能就没啥意义了。
Pragma和Expires同时使用，浏览器只听Pragma的，说明Pragma的优先级更高

### http1.1时代
1.Cache-Control 通用
针对上述的“Expires时间是相对服务器而言，无法保证和客户端时间统一”的问题，http1.1新增了 Cache-Control 来定义缓存过期时间，若报文中同时出现了 Pragma、Expires 和 Cache-Control，会以 Cache-Control 为准。
```
    Cache-Control: cache-directive
    //常用
    Cache-Control: max-age=3600
    Cache-Control: no-cache
```
作为请求首部和响应首部， cache-directive有可选的不同的值
> 问题引入:
客户端的资源缓存时间过期，需要重新发送请求，但此时服务器对应的资源并没有更新，再把该资源发送回去，是否会非常浪费带宽和时间？
是否有办法让服务器知道客户端现在存有的缓存文件，其实跟自己所有的文件是一致的，然后直接告诉客户端说“这东西你直接用缓存里的就可以了，我这边没更新过呢，就不再传一次过去了”。
要解决的就是缓存复用问题, http1.1新增了几个首部字段来解决这个问题

2.Last-Modified 实体（响应）首部字段-非通用
对应请求首部字段If-Modified-Since 和 If-Unmodified-Since
```
    //资源的最后修改时间
    Last-Modified: GMT
```
三步走：
a.服务器 -->资源--> 客户端(会把Last-Modified:GMT加在实体首部返回给客户端)
b.客户端会为资源标记上该GMT信息，下次再次请求时，会把该信息附带在请求报文中一并带给服务器去做检查
c.发送请求：若传递的时间值与服务器上该资源最终修改时间是一致的，则说明该资源没有被修改过，直接返回304状态码即可
怎么把服务器传来的“最终修改时间”传回去呢?
```
    If-Modified-Since: Last-Modified-value
//该请求首部告诉服务器如果客户端传来的最后修改时间与服务器上的一致，则直接回送304 和响应报头即可。
//当前各浏览器均是使用的该请求首部来向服务器传递保存的 Last-Modified 值。
    If-Unmodified-Since: Last-Modified-value(用的少)
```
3.Etag  响应首部字段
对应请求首部字段If-None-Match 和 If-Match
```
//服务器会通过某种算法，给资源计算得出一个唯一标志符（比如md5标志），在把资源响应给客户端的时候，会在响应报文首部加上“ETag: 唯一标识符”一起返回给客户端。
    ETag: 唯一标识符
```
整个过程跟“客户端”拿到“文件修改时间”类似
怎么把服务器传来的“唯一标识符”传回去呢?
```
    If-None-Match: ETag-value
//告诉服务器如果Etag匹配不上，那么直接以常规GET 200回包形式将新的资源（当然也包括了新的ETag）发给客户端；如果ETag是一致的，则直接返回304知会客户端直接使用本地缓存即可。
//当前各浏览器均是使用的该请求首部来向服务器传递保存的 ETag 值。
    If-Match: ETag-value(用得少)
```

**如果 Last-Modified 和 ETag 同时被使用，则要求它们的验证都必须通过才会返回304，若其中某个验证没通过，则服务器会按常规返回资源实体及200状态码。**

### 缓存实战
上面所提及的字段大部分会用到，例如使用 Expires 来兼容旧的浏览器，使用 Cache-Control 来更精准地利用缓存，然后开启 ETag 跟 Last-Modified 功能进一步复用缓存减少流量。

**Comment by sinner77** [comment]
### 强制缓存与协商缓存

| | 相关字段 | 状态码 | 获取资源的形式| 发送请求到服务器|
| ---  | :---:| :---:| ---: | ---: |
|强制缓存| Cache-Control,Expires|200（from cache） | 从本地缓存中获取 | 否，直接从本地缓存中读取 |
|协商缓存| Last-Modified与If-Modified-Since，Etag与If-None-Match|304（not modified）| 从本地缓存中获取 | 是，与浏览器协商本地缓存是否可用 |

### 浏览器读取缓存的整个过程
1. 浏览器第一次加载资源，服务器返回200，浏览器将资源文件从服务器上下载下来，并把response header及该请求的返回时间一并缓存；
2. 下一次加载资源时，先比较当前时间和上一次返回200时的时间差，如果没有超过cache-control设置的max-age，则没有过期，命中强缓存，不发请求直接从本地缓存读取该文件（如果浏览器不支持HTTP1.1，则用expires判断是否过期）；如果时间过期，则向服务器发送header带有If-None-Match和If-Modified-Since的请求；
3. 服务器收到请求后，优先根据Etag的值判断被请求的文件有没有做修改，Etag值一致则没有修改，命中协商缓存，返回304；如果不一致则有改动，直接返回新的资源文件带上新的Etag值并返回200；
4. 如果服务器收到的请求没有Etag值，则将If-Modified-Since和被请求文件的最后修改时间做比对，一致则命中协商缓存，返回304；不一致则返回新的last-modified和文件并返回200；

### 参考资料
[强制缓存与协商缓存](https://zhuanlan.zhihu.com/p/25953524)
[既生Last-Modified何生Etag](http://www.cnblogs.com/wonyun/p/5524617.html)

**Comment by sinner77** [comment]
**仅供参考**

**讲述Cache-Control与Last-Modified的区别?**

Cache-Control是对缓存时候的精确控制。它可以精确的限定缓存时间。
而Last-Modified存放的是文件最后修改时间，它对应请求头If-Modified-Since字段。If-Modified-Since存放的就是服务器传来的文件最后修改时间。
还有，Cache-Control是一种强制缓存，客户端无需发送请求到服务端确认本地缓存能否使用。从控制台来看就是200 from cache。
而Last-Modified是一种协商缓存，客户端需要发送请求到服务端确认本地缓存能否可用，如果If-Modified-Since的时候不与服务器端给的文件最后修改时间匹配，那么返回200和新的资源，如果匹配，则返回304。从控制台来看就是304 not modified。

返回的到期时间是服务器端的时间，这样存在一个问题，如果客户端的时间与服务器的时间相差很大，那么误差就很大


**有了Last-Modified,为什么还要Etag?**
Etag比lastModified更加严谨，如果资源发生变化，Etag就会发生变化，就会把最新的资源给客户端返回去，而lastModified不识别s（秒）单位里的修改，所以如果资源在s（秒）单位里发生了修改，那lastModified也不会发生改变，这样如果只用了lastModified，客户端得到的资源就不是最新的，Etag便不会有这样的情况。

**有了Etag,为什么还要Last-Modified?**
一些图片等静态文件的修改，如果每次扫描内容生成新Etag，跟直接比较文件修改时间肯定要慢许多。


> ETag 比较的是响应内容的特征值，而Last-Modified 比较的是响应内容的修改时间。

**Expires的缺点**
Expires所定义的缓存时间是相对服务器上的时间而言的，如果客户端上的时间跟服务器上的时间不一致（特别是用户修改了自己电脑的系统时间），那缓存时间可能就没啥意义了。

**Etag是怎么生成的？**

**Comment by twinkle77** [comment]
浏览器在获取资源时，缓存的获取优先级依次排列如下：
1. Memory Cache
2. Service Worker Cache
3. HTTP Cache
4. Push Cache（HTTP2 的新特性）

![image](https://user-images.githubusercontent.com/17792166/61191674-bd93ab00-a6df-11e9-91b2-633470ce79a1.png)

图片来自淘宝首页，可以看到Memory Cache花费的时间是0ms，这是浏览器从内存中读取的缓存，它的显示速度是最快的，但生命周期是最短的，当tab页关闭后，内存中的数据随着进程的消失而消失。
