### ISSUE TITLE
HTTP必知必会

### ISSUE THREAD

**Issue by twinkle77** [twinkle77/Knowledge-sharing#19]
* http的组成结构
* 常见的status code
* 常见的字段
* 缓存策略
* get和post的区别
* uri和url的区别
* 无状态的解决策略
* tcp三四次握手及其原因
* http标准http1.0和http1.1的区别

**Comment by sinner77** [comment]
## http知识点
定义：是一种计算机网络通信的规则，是一个基于请求与响应，无状态的，应用层的协议，常基于TCP/IP协议传输数据。

HTTP/1.1 定义的请求方法有8种：GET、POST、PUT、DELETE、PATCH、HEAD、OPTIONS、TRACE。

## http报文组成 
请求报文：

* 请求行
* 请求头
* 空行
* 请求体

响应报文：

* 状态行
* 响应头
* 空行
* 响应体

##  常用的首部字段
请求头和响应头的字段分类：

* 请求（响应）首部字段
* 通用首部字段
* 实体首部字段
* 其他

通用首部字段

| name | value |
| --- | --- |
| Content-Type | 请求体/响应体的类型，如：text/plain、application/json |
| Content-Length | 请求体/响应体的长度，单位字节 |
| Content-Encoding	| 请求体/响应体的编码格式，如gzip,deflate |
| Accept |	说明接收的类型，可以多个值，用,(半角逗号)分开 |
| Accept-Encoding | 告知对方我方接受的Content-Encoding |
| Cache-Control | 取值为一般为no-cache或max-age=XX，XX为个整数，表示该资源缓存有效期(秒) |

请求首部字段:

| name | value |
| --- | --- |
| If-Modified-Since |值为上一次服务器返回的 Last-Modified  值，用于确认某个资源是否被更改过，没有更改过(304)就从本地缓存中读取 |
| If-None-Match |值为上一次服务器返回的 ETag 值，一般会和If-Modified-Since一起出现|
| Cookie|已有的Cookie值|
| Authorization	| 用于设置身份认证信息 |
|Referer |表示请求引用自哪个地址，比如你从页面A跳转到页面B时，值为页面A的地址 |
| Host | 请求的主机和端口号 |
| User-Agent |	用户标识，如：OS和浏览器的类型和版本 |

响应首部字段:

| name | value |
| --- | --- |
| Last-Modified| 	该资源最后被修改的时间 | 
| Etag | 资源的唯一标识符 |
| Set-Cookie | 设置Cookie | 
| Location| 重定向到另一个URL | 
| Transfer-Encoding| 	取值为一般为chunked，出现在Content-Length不能确定的情况下，表示服务器不知道响应体的数据大小，一般同时还会出现Content-Encoding响应头| 
| Server| 后台服务器 | 
| Date	| 服务器的日期| 



## 常用的状态码

| --- | 类别 | 原因短语 |
| --- | --- | --- |
| 1xx | Infomational （信息性状态码）| 接收的请求正在处理 |
| 2xx | Success （成功状态码）| 请求正常处理完毕 |
| 3xx | Redirection （重定向状态码） | 要完成请求必须进行更进一步的操作 |
| 4xx | 	Client Error（客户端错误状态码） | 服务器无法处理请求 |
| 5xx | Server Error（服务器错误状态码) |服务器处理请求出错 |

#### 2XX
* 200 OK
* 204 No Content
* 206 Partial Content
200 表示从客户端发来的请求在服务器端被正常处理了。
204 一般在不需要对客户端发送新内容的情况下使用。表明服务器接受的请求已经成功处理，但返回的响应报文中不含实体的主体部分；
206 表示服务器成功执行了客户端发来的范围请求。响应报文中包含指定范围的实体内容。
#### 3XX
* 301 Moved Permanently
* 302 Found
* 303 See Other
* 304 Not Modified
* 307 Temporary Redirect
301 表示资源已经分配了新的 URI，以后都应该使用新的 URI。（永久重定向）
302 表示资源已经分配了新的 URI，仅仅这次用新的 URI 访问。（临时重定向）跳转地址通过响应头的location指定。
303 和 302 一样，只是要求必须用 GET 方法访问新的 URI。
304 使用本地缓存。常见于浏览器判断缓存是否过期。
307 和 302 一样。302 标准禁止 POST 变成 GET，实际大家并不遵守。307 会遵守这个标准，但处理时每种浏览器的行为有所不同。
#### 4XX
* 400 Bad Request
* 401 Unauthorized
* 403 Forbidden
* 404 Not Found
400 表示请求报文中有语法错误。
401 表示请求需要通过HTTP认证。若之前已经进行过一次请求，则表示用户认证失败。
403 表示请求的资源访问被服务器拒绝了。服务器不一定会给出拒绝的详细理由。
404 表示请求的资源不存在。也可以在服务器拒绝请求但不想说明理由的时候使用。
#### 5XX 
* 500 Internal Server Error
* 503 Service Unavailable
500 表示服务器在执行请求过程中发生了错误。
503 表示服务器暂时处于超负荷或者停机维护，暂时无法处理请求。


## 参考资料
[<<图解HTTP>>学习笔记](https://www.bokeyy.com/post/category/reading-notes/illustrate-http-protocol)
[HTTP请求与响应](http://www.jianshu.com/p/c1d6a294d3c0)
[HTTP Header](http://www.jianshu.com/p/59d36b01608d)

**Comment by sinner77** [comment]
**http标准http1.0和http1.1的主要区别?**

1. http1.1默认支持长连接，而http1.0默认不支持长连接，想要让http1.0支持长连接，需要手动添加connection:keep-alive。
2. HTTP 1.0不支持Host请求头字段。在http1.1新增了Host请求头字段，让客户端可以明确表示要访问服务器上的哪个web站点。实现了在一台服务器上可以在同一个IP地址和端口号上使用不同的主机名来创建多个虚拟WEB站点。
3. HTTP 1.1支持只发送header信息(不带任何body信息)，如果服务器认为客户端有权限请求服务器，则返回100，否则返回401。客户端如果接受到100，才开始把请求body发送到服务器。

**Comment by sinner77** [comment]
**get和post的区别?**

1. 从语义来看，get的语义是获取/查询资源信息,post的语义是根据请求体对指定的资源做出处理
2. 从性质来看，get是幂等，可缓存的，而post是不幂等，不可缓存的。
> 幂等的意味着对同一URL的多个请求返回同样的结果

3. 从现象来看
    1. get请求的数据会附在URL之后，post提交的数据放置在请求体中
    2. get请求向URL添加的数据长度是有限制的，一般URL的最大长度为2048,而post无限制
    3. post请求相对get请求更安全。(get请求换缓存在浏览器历史记录中)
    4. 发送请求时，请求头的Content-Type字段值不同。即编码类型不同
